### ISSUE TITLE
Issue in config.php file: missing dependency

### ISSUE THREAD

**Issue by cfecherolle** [fmancardi/JWTSSO#1]
Hello,

First of all thank you for making this plugin, it helped me understand how authentication works in MantisBt altogether: really interesting!

I have an issue in config.php file (config page for the plugin in administration) because I can't find the class helperMethodsPlugin which should have a drawinputTextRow method. Because of this, the page itself is broken, so I would like to know where I can find this specific method?

Thanks!

Regards,
Cécile

**Comment by kapi-jk** [comment]
Hi Cecile,

I think, that has to be removed for a while as I could not find any reference for this.
Anyway, I just replaced it with
`echo '<tr>';`
` echo '    <th class="category">';`
 `echo '        <label for="'.$op.'">'.plugin_lang_get( $op ).'</label>';`
` echo '    </th>';`
 `echo '    <td><input type="text" id="'.$op.'" name="'.$op.'" value="'.$val.'" size="'.$elem['opt']['size'].'" size="'.$elem['opt']['maxlenght'].'"/></td>';`
` echo '</tr>';`
And this seems to work for the configuration. I'm still to verify the rest of the functionality. I might then do some fix to the code if there isn't anything else required.

kapi

**Comment by cfecherolle** [comment]
Hi,

Thank you, it has been a few years since I used MantisBt so I don't even remember what this was about. Hope it helps others :)
